### ISSUE TITLE
Typo in paper title

### ISSUE THREAD

**Issue by samcmill** [HPCSYSPROS/Workshop18#1]
I just noticed there's a typo in the BibTeX citation and repository path for my paper.

The paper title is "Making Container*s* Easier with HPC Container Maker" (note the second word is plural).

The 's' in "Containers" is missing from the repository path, README.md, and citation.bib.

**Comment by stephenlienharrell** [comment]
Fixed in c228b2287addc626d1863afbf3f6bba99db47f26
